### PR TITLE
Initial express server and skeleton apis

### PR DESCRIPTION
**Pull request by ethanduncan**
Leaving PR open to discuss API's with @domgoodwin 

No need to merge yet.

### CODE REVIEW

**Comment by domgoodwin** [comment]
API's discussed and created based off current miner functionality. Some miner functionality identified as TODO and will be done this weekend.

**Comment by johnog65536** [comment]
Going to try to finish the java based cmd line wallet this weekend too
Did you do an example of how to call the miner anywhere

**Comment by domgoodwin** [comment]
Start the server using 'node server.js'
All the calls will be REST calls to localhost:8080/api(I think)

I'll document all of them fully but if you look through server.js there are GETs and POSTs to different routes, ie (GET localhost:8080/api/blockchain) gives you the whole chain active in the miner back

**Comment by domgoodwin** [comment]
8080 not 3000

**Pull request merged**
