### PR TITLE
Miner todo implementation

### PR DESCRIPTION
**Pull request by domgoodwin**
Implementation of the TODO functions in the miner and blockchain

### CODE REVIEW

**Comment by johnog65536** [comment]
Ignore this comment - was because I had dodgy post bodies. Now fixed




Have pushed up an updated miner client (TestHttpCallOnMiner). It successfully passes messages into create transaction and get pending list, but errors (HTTP 500) when calling the confirm transaction method - from the node output:

```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Miner.confirm (C:\Users\jogden\Desktop\java\projects\Currency\node-server\miner.js:33:27)
    at Object.handle (C:\Users\jogden\Desktop\java\projects\Currency\node-server\server.js:48:30)
    at next_layer (C:\Users\jogden\Desktop\java\projects\Currency\node-server\node_modules\express\lib\router\route.js:103:13)
    at Route.dispatch (C:\Users\jogden\Desktop\java\projects\Currency\node-server\node_modules\express\lib\router\route.js:107:5)
    at C:\Users\jogden\Desktop\java\projects\Currency\node-server\node_modules\express\lib\router\index.js:195:24
    at Function.proto.process_params (C:\Users\jogden\Desktop\java\projects\Currency\node-server\node_modules\express\lib\router\index.js:251:12)
    at next (C:\Users\jogden\Desktop\java\projects\Currency\node-server\node_modules\express\lib\router\index.js:189:19)
    at next (C:\Users\jogden\Desktop\java\projects\Currency\node-server\node_modules\express\lib\router\index.js:166:38)
    at next (C:\Users\jogden\Desktop\java\projects\Currency\node-server\node_modules\express\lib\router\index.js:166:38)
```

The pending transaction file looks like this

`{"transactions":[{"fee":0,"confirmations":0,"time":1512923249962,"details":[{"category":"send","amount":null,"fee":0},{"category":"recieve"}],"txId":"1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"},{"fee":0,"confirmations":0,"time":1512923250165,"details":[{"category":"send","amount":null,"fee":0},{"category":"recieve"}],"txId":"1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"},{"fee":0,"confirmations":0,"time":1512923250197,"details":[{"category":"send","amount":null,"fee":0},{"category":"recieve"}],"txId":"1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"},{"fee":0,"confirmations":0,"time":1512923250246,"details":[{"category":"send","amount":null,"fee":0},{"category":"recieve"}],"txId":"1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"},{"fee":0,"confirmations":0,"time":1512923250251,"details":[{"category":"send","amount":null,"fee":0},{"category":"recieve"}],"txId":"1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"},{"fee":0,"confirmations":0,"time":1512923712042,"details":[{"category":"send","amount":null,"fee":0},{"category":"recieve"}],"txId":"1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"},{"fee":0,"confirmations":0,"time":1512923712080,"details":[{"category":"send","amount":null,"fee":0},{"category":"recieve"}],"txId":"1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"},{"fee":0,"confirmations":0,"time":1512923712097,"details":[{"category":"send","amount":null,"fee":0},{"category":"recieve"}],"txId":"1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"},{"fee":0,"confirmations":0,"time":1512923712119,"details":[{"category":"send","amount":null,"fee":0},{"category":"recieve"}],"txId":"1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"},{"fee":0,"confirmations":0,"time":1512923712130,"details":[{"category":"send","amount":null,"fee":0},{"category":"recieve"}],"txId":"1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"},{"fee":0,"confirmations":0,"time":1512923847012,"details":[{"category":"send","amount":null,"fee":0},{"category":"recieve"}],"txId":"1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"},{"fee":0,"confirmations":0,"time":1512923847071,"details":[{"category":"send","amount":null,"fee":0},{"category":"recieve"}],"txId":"1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"},{"fee":0,"confirmations":0,"time":1512923847124,"details":[{"category":"send","amount":null,"fee":0},{"category":"recieve"}],"txId":"1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"},{"fee":0,"confirmations":0,"time":1512923879726,"details":[{"category":"send","amount":null,"fee":0},{"category":"recieve"}],"txId":"1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"},{"fee":0,"confirmations":0,"time":1512923879756,"details":[{"category":"send","amount":null,"fee":0},{"category":"recieve"}],"txId":"1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"},{"fee":0,"confirmations":0,"time":1512923879772,"details":[{"category":"send","amount":null,"fee":0},{"category":"recieve"}],"txId":"1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"},{"fee":0,"confirmations":0,"time":1512923879802,"details":[{"category":"send","amount":null,"fee":0},{"category":"recieve"}],"txId":"1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"},{"fee":0,"confirmations":0,"time":1512923879819,"details":[{"category":"send","amount":null,"fee":0},{"category":"recieve"}],"txId":"1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"},{"fee":0,"confirmations":0,"time":1512923899804,"details":[{"category":"send","amount":null,"fee":0},{"category":"recieve"}],"txId":"1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"},{"fee":0,"confirmations":0,"time":1512923899831,"details":[{"category":"send","amount":null,"fee":0},{"category":"recieve"}],"txId":"1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"},{"fee":0,"confirmations":0,"time":1512923899854,"details":[{"category":"send","amount":null,"fee":0},{"category":"recieve"}],"txId":"1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"},{"fee":0,"confirmations":0,"time":1512923899880,"details":[{"category":"send","amount":null,"fee":0},{"category":"recieve"}],"txId":"1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"},{"fee":0,"confirmations":0,"time":1512923913953,"details":[{"category":"send","amount":null,"fee":0},{"category":"recieve"}],"txId":"1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"},{"fee":0,"confirmations":0,"time":1512923913994,"details":[{"category":"send","amount":null,"fee":0},{"category":"recieve"}],"txId":"1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"},{"fee":0,"confirmations":0,"time":1512923914013,"details":[{"category":"send","amount":null,"fee":0},{"category":"recieve"}],"txId":"1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"},{"fee":0,"confirmations":0,"time":1512923914055,"details":[{"category":"send","amount":null,"fee":0},{"category":"recieve"}],"txId":"1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"},{"fee":0,"confirmations":0,"time":1512923914064,"details":[{"category":"send","amount":null,"fee":0},{"category":"recieve"}],"txId":"1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"},{"fee":0,"confirmations":0,"time":1512924077100,"details":[{"category":"send","amount":null,"fee":0},{"category":"recieve"}],"txId":"1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"},{"fee":0,"confirmations":0,"time":1512924077134,"details":[{"category":"send","amount":null,"fee":0},{"category":"recieve"}],"txId":"1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"},{"fee":0,"confirmations":0,"time":1512924077150,"details":[{"category":"send","amount":null,"fee":0},{"category":"recieve"}],"txId":"1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"},{"fee":0,"confirmations":0,"time":1512924077183,"details":[{"category":"send","amount":null,"fee":0},{"category":"recieve"}],"txId":"1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"},{"fee":0,"confirmations":0,"time":1512924157336,"details":[{"category":"send","amount":null,"fee":0},{"category":"recieve"}],"txId":"1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"},{"fee":0,"confirmations":0,"time":1512924157360,"details":[{"category":"send","amount":null,"fee":0},{"category":"recieve"}],"txId":"1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"},{"fee":0,"confirmations":0,"time":1512924157384,"details":[{"category":"send","amount":null,"fee":0},{"category":"recieve"}],"txId":"1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"},{"fee":0,"confirmations":0,"time":1512924157402,"details":[{"category":"send","amount":null,"fee":0},{"category":"recieve"}],"txId":"1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"},{"fee":0,"confirmations":0,"time":1512924157405,"details":[{"category":"send","amount":null,"fee":0},{"category":"recieve"}],"txId":"1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"}]}`


Testing output is below:
` 

registerGenesysKeysPost() Posting to : requestjson={"name":"Genesys Key Pair","pubKey":"MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKlwIkozgp87m8tK5pTfkGYqFdEjlPZtrT72ETVRXpLD7w1QNPXrZvisCoYsk1YPA4gXjpPrnmaBLL+nq2Y3K4kCAwEAAQ\u003d\u003d","privKey":"MIIBVgIBADANBgkqhkiG9w0BAQEFAASCAUAwggE8AgEAAkEAqXAiSjOCnzuby0rmlN+QZioV0SOU9m2tPvYRNVFeksPvDVA09etm+KwKhiyTVg8DiBeOk+ueZoEsv6erZjcriQIDAQABAkBY1MA1dLH7t22jdD5VOKxk05WikuwLEk8s3icBdAqIGLIF4OZydSinC6aG5KbOX5xoGdCeQ/lG1AM6VOSI0cIBAiEA89uJbfof7QjMvuYcmMUqE/06tBZmeU5FQVrrVh0tN8ECIQCx3/fJK+KFSG/bnTy81DdQD7zRQDQbSny18l+UcoelyQIhANEhWX7jnzWc8lpU5fluPWPfK9T90Ov/YA1od6Lmar0BAiEAgPEumnJpntzH2Ze+M9RS1ILUCYxVOYNhrDOq/d2YX6ECIQCKiW4LTJu41yym3bjH2B0z2p9GLvs9WtTXEzhGDvyk4w\u003d\u003d"}
registerGenesysKeysPost() : {"message":"Transaction created: 1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"}

createSimpleTransaction() Posting to : http://localhost:8080/api/create requestjson={"amount":10.0,"fromAddress":"MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKlwIkozgp87m8tK5pTfkGYqFdEjlPZtrT72ETVRXpLD7w1QNPXrZvisCoYsk1YPA4gXjpPrnmaBLL+nq2Y3K4kCAwEAAQ\u003d\u003d","toAddress":"MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIqYY20YFpJ8DAA5bZ7Vr2gHKj4FCwAWZaITi0caOJ22XaFrBsJ4iarbBwTNIUl9nSHxwTsvskUJ/9CjYHMqEsECAwEAAQ\u003d\u003d","comment":"Pay from the genesis key to MyFirstKey!"}
createSimpleTransaction() response: {"message":"Transaction created: 1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"}

createSimpleTransaction() Posting to : http://localhost:8080/api/create requestjson={"amount":5.0,"fromAddress":"MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIqYY20YFpJ8DAA5bZ7Vr2gHKj4FCwAWZaITi0caOJ22XaFrBsJ4iarbBwTNIUl9nSHxwTsvskUJ/9CjYHMqEsECAwEAAQ\u003d\u003d","toAddress":"MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJnDwh80ANS0FSVmUbi7bSpXo0O0eQKbaupesj8egJUNQDyPD6bBdYT58nUJXEkJ6rYlGxqvOmdhJb+j1VZvJccCAwEAAQ\u003d\u003d","comment":"Pay from MyFirstKey to MySecondKey!"}
createSimpleTransaction() response: {"message":"Transaction created: 1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"}

createSimpleTransaction() Posting to : http://localhost:8080/api/create requestjson={"amount":2.0,"fromAddress":"MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIqYY20YFpJ8DAA5bZ7Vr2gHKj4FCwAWZaITi0caOJ22XaFrBsJ4iarbBwTNIUl9nSHxwTsvskUJ/9CjYHMqEsECAwEAAQ\u003d\u003d","toAddress":"MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBANF8L8ZykQVVU6YVhw+wsP7IoBOG2oXy1FY1CL6IL1FsZwKxlNobWCQ6V9dtOyKGJgJELj9qw+3Fcuy1+5Ty+pMCAwEAAQ\u003d\u003d","comment":"Pay from MyFirstKey to MyThirdKey!"}
createSimpleTransaction() response: {"message":"Transaction created: 1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"}

createSimpleTransaction() Posting to : http://localhost:8080/api/create requestjson={"amount":2.0,"fromAddress":"MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJnDwh80ANS0FSVmUbi7bSpXo0O0eQKbaupesj8egJUNQDyPD6bBdYT58nUJXEkJ6rYlGxqvOmdhJb+j1VZvJccCAwEAAQ\u003d\u003d","toAddress":"MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBANF8L8ZykQVVU6YVhw+wsP7IoBOG2oXy1FY1CL6IL1FsZwKxlNobWCQ6V9dtOyKGJgJELj9qw+3Fcuy1+5Ty+pMCAwEAAQ\u003d\u003d","comment":"Pay from MySecondKey to MyThirdKey!"}
createSimpleTransaction() response: {"message":"Transaction created: 1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5"}

getPendingTransactions() : {"transaction":""}

getConfirmedTransactions NOT YET IMPLEMENTED - needs store transaction ID

goMine() Posting to : http://localhost:8080/api/confirm-transactions

 `

**Comment by johnog65536** [comment]
Issue with the miner's create transaction method - it always seems to return 1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5 as the transaction ID

**Comment by domgoodwin** [comment]
Using the exact same pending transactions file I was able to confirm them all successfully. I'll have a play around with end but is there a chance its either being called twice or called very closely to the create transaction where the file is used?

**Comment by johnog65536** [comment]
have added some delays and checked no duplicate transactions & pushed to master

transaction hash still comes back with 1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5 in all cases regardless of what keys are used to send/receive

And the confirm Transactions method very frequently stops with 
```

SyntaxError: Unexpected token , in JSON at position 0
    at JSON.parse (<anonymous>)
    at Miner.confirm (C:\Users\jogden\Desktop\java\projects\Currency\node-server\miner.js:33:27)
    at Object.handle (C:\Users\jogden\Desktop\java\projects\Currency\node-server\server.js:48:30)
```

**Comment by johnog65536** [comment]
I trashed all the json files in the working dir & miner started to work again.  No more parse errors. Ran the tests about 10 times and it went back to failing. Deleted the 2 json files and it went back to working again. So I think there is a buffer issue somewhere when it reads the blockchain in the mine method - not a big deal for now as easy to bodge

Every time I run create transaction though, it returns the same txn id: 1cdf925e1fd854978b1e1becc8ef946d2c9a1623ceae1e22a78641b2761d5ef5 if you could take a look at that please

**Comment by domgoodwin** [comment]
I've added in a more robust check when it reads the file in as I think that was causing the issues.

I'll check the transaction id thing now as it should generate from the data.

**Comment by johnog65536** [comment]
Cheers - am going to knock of for tea

**Comment by domgoodwin** [comment]
Transaction id now fixed and tested locally through the API. Happy to merge.

**Comment by johnog65536** [comment]
I have the updates to miner, server and transaction - but still getting the duplicate txn id?

**Comment by johnog65536** [comment]
Closed & merged - finally twigged this was an issue in the client side. I was sending a badly formed create transaction post body. Is a bit hacky, but sorted it now

**Pull request merged**
